stages: 
  - build
GenerateHTML:
  stage: build
  script:
    - echo "current directory:"$(pwd)
    - echo "ip address:"$(ip addr|grep 'enp'|grep 'inet'|cut -d'/' -f1|cut -d" " -f6)
    - echo "ip address:"$(ip addr)
    - gitbook build
    - chmod +x start.sh
    - sh start.sh
    - echo "complete ...... "
  tags:
    - build